package eu.ubitech.sma.repository.domain;
// Generated Sep 17, 2014 12:03:28 PM by Hibernate Tools 3.6.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * City generated by hbm2java
 */
@Document
public class City implements Serializable {

    @Id
    private String id;
    private Province province;
    private int rank;
    private String city;
    private int population;
    private Set individuals = new HashSet(0);

    public City() {
    }

    public City(Province province, int rank, String city, int population) {
        this.province = province;
        this.rank = rank;
        this.city = city;
        this.population = population;
    }

    public City(Province province, int rank, String city, int population, Set individuals) {
        this.province = province;
        this.rank = rank;
        this.city = city;
        this.population = population;
        this.individuals = individuals;
    }

    
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Province getProvince() {
        return this.province;
    }

    public void setProvince(Province province) {
        this.province = province;
    }

    public int getRank() {
        return this.rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public int getPopulation() {
        return this.population;
    }

    public void setPopulation(int population) {
        this.population = population;
    }

    public Set getIndividuals() {
        return this.individuals;
    }

    public void setIndividuals(Set individuals) {
        this.individuals = individuals;
    }

}
