package eu.ubitech.sma.repository.domain;
// Generated Sep 17, 2014 12:03:28 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * PostMeta generated by hbm2java
 */
@Document
public class PostMeta  implements java.io.Serializable {


     private Integer id;
     private int postId;
     private Set posts = new HashSet(0);

    public PostMeta() {
    }

	
    public PostMeta(int postId) {
        this.postId = postId;
    }
    public PostMeta(int postId, Set posts) {
       this.postId = postId;
       this.posts = posts;
    }
   
     @Id
     public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    public int getPostId() {
        return this.postId;
    }
    
    public void setPostId(int postId) {
        this.postId = postId;
    }

    public Set getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set posts) {
        this.posts = posts;
    }




}


