package eu.ubitech.sma.repository.domain;
// Generated Sep 17, 2014 12:03:28 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * PostStatus generated by hbm2java
 */
@Document
public class PostStatus  implements java.io.Serializable {


    @Id
     private String id;
     private String description;

    public PostStatus() {
    }

    public PostStatus(String description) {
       this.description = description;
    }
   
     
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


