package eu.ubitech.sma.repository.domain;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Province generated by hbm2java
 */
@Document
public class Province implements Serializable {

    @Id
    private String id;
    private String name;
    private Set individuals = new HashSet(0);
    private Set cities = new HashSet(0);

    public Province() {
    }

    public Province(String name) {
        this.name = name;
    }

    public Province(String name, Set individuals, Set cities) {
        this.name = name;
        this.individuals = individuals;
        this.cities = cities;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getIndividuals() {
        return this.individuals;
    }

    public void setIndividuals(Set individuals) {
        this.individuals = individuals;
    }

    public Set getCities() {
        return this.cities;
    }

    public void setCities(Set cities) {
        this.cities = cities;
    }

}
